name: Client E2E tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Login-With-Auth0:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: List current NODE_VERSION
        run: echo "The current version is ${{vars.NODE_VERSION}}"
      # - name: Setup Node ${{vars.NODE_VERSION }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{vars.NODE_VERSION}}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache NPM and Cypress
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/Cypress
            /server/node_modules
            /client/node_modules
          key: my-cache-${{runner.os}}-${{hashFiles('/client/package-lock.json')}}
      - name: Install Cypress
        run: npm i cypress@12.8.1
      - name: Cypress run
        uses: ./
        with:
          install: false
          browser: firefox