name: Client E2E tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Login-With-Auth0:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: List current NODE_VERSION
        run: echo "The current version is ${{vars.NODE_VERSION}}"
      - uses: actions/checkout@v3
      - name: Use Node.js ${{vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{vars.NODE_VERSION}}
      - name: Cypress run
        uses: cypress-io/github-action@v5.5.1
        with:
          browser: firefox
          build: npm run buildClient && npm run buildServer
          start: npm run startClient && npm run startServer