name: Cypress E2E CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{vars.NODE_VERSION}}
      - name: List files in /server directory
        run: |
          ls ${{github.workspace}}/server
      - name: List files in /client directory
        run: |
          ls ${{github.workspace}}/client
      - name: List current NODE_VERSION
        run: echo "The current version is ${{vars.NODE_VERSION}}"
      - name: Install dependencies
        run: npm ci
      - name: Install client dependencies
        run: npm run install:client
  build-directories:
    runs-on: ubuntu-latest
    needs: build-project
    outputs:
      client: ${{ steps.build-client.outputs.client }}
      server: ${{ steps.build-server.outputs.server }}
    steps:
      - id: build-server
        run: |
          npm run build:server &
          sleep 30 && echo "server=ready" >> "$GITHUB_OUTPUT"
      - id: build-client
        run: |
          npm run build:client &
          sleep 30 && echo "client=ready" >> "$GITHUB_OUTPUT"
  start-servers:
    runs-on: ubuntu-latest
    needs: build-directories
    steps:
      - env:
          CLIENT: ${{ needs.build-directories.outputs.client }}
          SERVER: ${{ needs.build-directories.outputs.server }}
        run: |
          echo "The client directory is $CLIENT and the server directory is $SERVER" &&
          npm run cypress:run
