name: Cypress E2E CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{vars.NODE_VERSION}}
      - name: List files in /server directory
        run: |
          ls ${{github.workspace}}/server
      - name: List files in /client directory
        run: |
          ls ${{github.workspace}}/client
      - name: List current NODE_VERSION
        run: echo "The current version is ${{vars.NODE_VERSION}}"
      - name: Install dependencies
        run: npm ci
      - name: Install client dependencies
        run: npm run install:client
      - name: Build and start client and server
        # NOTE it only takes about ~1sec for the client to be built apparently, and so it finishes building much much sooner than the server
        # and so what appears to be happening in the tests is that the client boots up, and you can see the output of the curl command where it is the raw document of the page and shows the error boundary for that page and returns a 500 internal server error
        # THEN the server finishes building and starts, then the cypress test starts, and the test fails instally because it can't visit localhost:3000 due to that 500 server error
        # Which means either that the test tries to access the site before the server is ready and the client connects to it properly OR that the client NEVER connects to the server properly when it starts up first
        # The 500 server error indicates that the issue does pertain to the server, and the client's inability to connect
        run: |
          npm run start:server &
          npm run start:client &
          sleep 30
      - name: Run Cypress tests
        run: npm run cypress:run
      - name: Archive Cypress videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: /client/cypress/videos
