name: Cypress E2E CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{vars.NODE_VERSION}}
      - name: List files in /server directory
        run: |
          ls ${{github.workspace}}/server
      - name: List files in /client directory
        run: |
          ls ${{github.workspace}}/client
      - name: List current NODE_VERSION
        run: echo "The current version is ${{vars.NODE_VERSION}}"
      - name: Install dependencies
        run: npm ci
      - name: Install client dependencies
        run: npm run install:client
      - name: Build and start client and server
        run: |
          npm run start:client &
          npm run start:server &
          sleep 10 &&
          curl http://localhost:3000
      - name: Run Cypress tests
        run: npm run cypress:run
