name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{vars.NODE_VERSION}}
      - name: List files in /server directory
        run: | 
          ls ${{github.workspace}}/server
      - name: List current NODE_VERSION
        run: echo "The current version is ${{vars.NODE_VERSION}}"
      - name: Run unit tests
        run: npm ci
      - run: npm run serverUnitTests
